services:
  ui:
    build:
      context: .
      target: dev
    container_name: hm_ui
    restart: "no"
    networks:
      - hm_network

networks:
  hm_network:
    name: hm_network
    external: true
